# Generated by Django 5.0.6 on 2025-08-03 03:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_alter_curso_imagen_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-created'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividad'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracion_horas',
        ),
        migrations.AddField(
            model_name='curso',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=20, help_text='Duración en horas'),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermedio'), ('A', 'Avanzado')], default='B', max_length=1),
        ),
    ]
